import Navbar from "@/Components/Navbar/Navbar";
import Footer from "@/Components/Footer/Footer";
import "@/app/globals.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className=" max-w-screen-2xl flex flex-col justify-between m-auto pl-[50px] pr-[50px] min-h-screen">
          <header>
            <Navbar />
          </header>
          <div className="items-center">{children}</div>
          <footer>
            <Footer />
          </footer>
        </div>
      </body>
    </html>
  );
}
